### ISSUE TITLE
Pip install (using virtualenv) places crypt_keys in wrong directory

### ISSUE THREAD

**Issue by folz** [02strich/python-pandora#1]
When installing python-pandora from pip, the crypt_key_*.h files are incorrectly placed in the current directory. This leads to the error

> IOError: [Errno 2] No such file or directory: 'venv/lib/python2.7/site-packages/pandora/crypt_key_output.h'

because crypt_key_output.h is actually located in 'venv/pandora/crypt_key_output.h'
##### Steps to reproduce:

`$ mkdir some_folder && cd some_folder`

`$ virtualenv venv --distribute && source venv/bin/activate`

`$ pip install python-pandora`

> [...]
> warning: no files found matching 'pandora\crypt_key_*.h'
> [...]
##### Which results in

`$ cat venv/lib/python2.7/site-packages/python_pandora-0.6_33/installed-files.txt`

> [...]
> ../pandora/keys.pyc
> ../pandora/connection.pyc
> ../../../../pandora/crypt_key_input.h
> ../../../../pandora/crypt_key_output.h
> ./
> top_level.txt
> [...]

`$ ls venv/`

> bin/  include/  lib/  lib64@  pandora/

**Comment by 02strich** [comment]
Thanks for the information (and very good description), c7f858499d71bee141011f7fd1d7293f0bbf6af0 should have fixed this and I uploaded a new version on PyPi

**Comment by folz** [comment]
That did it, thanks!
