### ISSUE TITLE
Switch station

### ISSUE THREAD

**Issue by Gh0stWires** [02strich/python-pandora#8]
I am wondering how does your switch station function works? I know you can switch based on the integer in the list of the stations. But can you switch based on the string of the station name?

**Comment by 02strich** [comment]
why did you re-open this?

**Comment by Gh0stWires** [comment]
Because i figured away around so thats why i closed it but now the problem is unavoidable in another application I'm making.

**Comment by 02strich** [comment]
Ok, could you refresh my memory on what the exact issue is you are encountering?

**Comment by Gh0stWires** [comment]
I'm trying to figure out a way to switch stations based on the station selected in a list of stations. I was able to do this in the desktop version because gtk selection box has a function to get the active cell which returns an integer and that integer corresponds with the position of the station in pandora.stations. But on the mobile app i can only seem to get seem to get the string of the station. I'm not 100% sure how to phrase the question but I can show you the code if needed.

**Comment by 02strich** [comment]
You can allways simply scan the stations list on the Pandora instance for any property you like and submit the matching entry to the switch_station function.

**Comment by Gh0stWires** [comment]
could you give me an example of what you mean?

**Comment by 02strich** [comment]
sure:

```
for station in pandora.stations:
    if station['stationName'] == new_station_name:
        pandora.switch_station(station)
        break
```

**Comment by Gh0stWires** [comment]
Thanks that works. thanks for all your help man I mean it. Without it I wouldn't be able to finish my project and of course your awesome library.

**Comment by 02strich** [comment]
you are more then welcome
