### ISSUE TITLE
Question about the get_next_song() function

### ISSUE THREAD

**Issue by Gh0stWires** [02strich/python-pandora#9]
I really just want to understand how the function works better.

**Comment by 02strich** [comment]
Yes it takes a moment, if it has to fetch infos from pandora, but it should actually allways return something. Could you elaborate a little bit more on what you do? Also are you using the latest python-pandora Version?

**Comment by Gh0stWires** [comment]
http://pastebin.com/hCFMnm7A heres a piece of the code. basically. a play button is clicked and that play function is called. now the skip function clears what was previously on the player and does the same thing that the play function does.

**Comment by 02strich** [comment]
hey,

the get_next_song function checks the internal information buffer (called backlog) for enough information. If not enough entries are left, new ones are fetched from pandora. Either way the next entry from the backlog is returned. This means, that the function every so often talks to the Pandora servers and might be slow. Does this answer your question?

**Comment by Gh0stWires** [comment]
so How would i go about returning the next song in the backlog?

**Comment by 02strich** [comment]
That is what get_next_song does ....

**Comment by Gh0stWires** [comment]
so if I wanted the next song i would just call it again?

**Comment by 02strich** [comment]
yes, exactly

**Comment by Gh0stWires** [comment]
doesn't seem to work though. if I assign it to the variable again it gives me an error. if i just call pandora.get_next_song() it just replays the current song.

**Comment by 02strich** [comment]
If you run "self.ns = pan.get_next_song()" again it raises an exception? Could you post a stacktrace?

If you call get_next_song again, off cause it will not change what is played back as it does not know about your playback logic.

**Comment by Gh0stWires** [comment]
Traceback (most recent call last):
  File "./anarchyRadio.py", line 108, in next_track
    self.player.set_property("uri",str(self.ns['audioUrlMap']['highQuality']['audioUrl']))
KeyError: 'audioUrlMap'

**Comment by 02strich** [comment]
could you post the value of self.ns when that happens please?

**Comment by Gh0stWires** [comment]
Value as in what it returns?

**Comment by 02strich** [comment]
value as in value of the variable, i.e. what does repr(self.ns) return?

**Comment by Gh0stWires** [comment]
{u'adToken': u'1476880292430959040-none'}. I have to go to work so i wont be able to respond for a bit.

**Comment by 02strich** [comment]
Ok, have a produktive day. I assume you do not have Pandora One? In that case you have to filter out the ads, by checking for the adtoken and fetch again in that case...

**Comment by Gh0stWires** [comment]
I changed my code and got it working. Now everytime it sees an adToken it ignores it and grabs another song. Thanks for your help.

**Comment by 02strich** [comment]
you are welcome, will make a note to implement the skipping in the lib itself
